---
# tasks file for logwatch

- name: Install logwatch packages
  package:
    name: "{{ item }}"
    state: present
  with_items:
    - "{{ logwatch_packages }}"
    - "{{ logwatch_additional_packages }}"
  tags:
    - package
    - logwatch

- name: Create Temp Folder
  file:
    path: /var/cache/logwatch
    state: directory
    owner: root
    group: root
    mode: 0755
  tags:
    - setup
    - logwatch

- name: Create logwatch configuration
  when: logwatch_config_files | length > 0
  template:
    src: "{{ item }}"
    dest: "/etc/logwatch/conf/{{ item | basename | replace('.j2', '') }}"
    owner: root
    group: root
    mode: 0644
  with_items:
    - "{{ logwatch_config_files }}"
  tags:
    - config
    - logwatch
